name: UHD.io
favicon: null
layout_spectrum: 0.86666
typography_spectrum: 0.26784
title: 4K Ultra HD (UHD) News and more
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-20866705-8
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
